### ISSUE TITLE
Error is getting in First Challenge || command used  #terraform apply

### ISSUE THREAD

**Issue by L4stPL4Y3R** [BishopFox/cloudfoxable#10]
Hi Team,
I want to solve first challenge of cloudfoxable. I am getting error even after set new account with administrator access. 

#### Screenshots / Files
Command:
**#terraform apply** 
![Error](https://github.com/BishopFox/cloudfoxable/assets/26342194/342e87ef-f44a-4ff5-a4ff-93d173f1cdcd)

Can you help me to solve this error.

**Comment by sethsec-bf** [comment]
It looks like your `cloudfox` user does not have the permissions to deploy the resources to your account with terraform. It also looks like you did successfully configure your profile and that the user account itself is working, it's just a permissions issue. I'd take a look at that user in the console and see if you successfully attached the AdministrativeAccess policy to it. Here's mine: 

![image](https://github.com/BishopFox/cloudfoxable/assets/46326948/edcab4cb-eaec-4ed6-9f9e-d10e353035df)

Here's the reference guide for creating an admin user: https://docs.aws.amazon.com/IAM/latest/UserGuide/getting-set-up.html#create-an-admin

**Comment by sethsec-bf** [comment]
Ohh, i see two different account numbers in your terrafrom error messages. You are deploying with arn::::82955...:/user/cloudfox, but it looks like you are deploying into account that starts with 5363....  

Can you share what changes you have made to `terraform.tfvars`?  are you using the default profile or another one? did you. uncomment https://github.com/BishopFox/cloudfoxable/blob/main/aws/terraform.tfvars.example#L14 or leave it commented?  thanks!

**Comment by sethsec-bf** [comment]
when you do `aws sts get-caller-identity --profile cloudfoxable`, what user do you get. is it the user cloudfox from the screenshot above, or is it ctf-starting-user? 

there are two users minimum users/profiles to successfully use cloudfoxable. 

the first one is your deployer role. you can name it whatever you want and you give it admin access like you did in that screenshot and that is the one you need to create keys for, make a profile for, and then use that profile here: 

aws_local_profile = "cloudfoxableDeployer" 
the second, is the one that is created as part of of the terraform apply and is the one you then need to create under the cloudfoxable profile. 

I think that migght be hte issue here. if you used cloudfoxable for the name of your first profile, then maybe the copy/paste code from the terraform overwrite that first profile or created a second profile with teh same name.  

Make sure your first deployer profile is working and returuns the cloudfox user from the screenshot using sts get caller identity. make sure the name is other than cloudfoxable, and then change aws_local_profile = to be the new name.  

then use the copy/paste command from terraform output to make the cloudfoxable profile that you will use for the challenges. 

hopefully this fixes it.  let me know.

**Comment by L4stPL4Y3R** [comment]
Hi,

I have reconfigured and a snapshot of all configurations and the Error is as below.
![image](https://github.com/BishopFox/cloudfoxable/assets/26342194/16f3d033-212b-43bc-a403-511f9deba5e9)

![image](https://github.com/BishopFox/cloudfoxable/assets/26342194/2efa6fbb-2a98-460c-8ddd-6095c61fd330)

Thank you
