### ISSUE TITLE
challenge.yaml files to add

### ISSUE THREAD

**Issue by pve** [BishopFox/cloudfoxable#12]
As a CTFd event organiser
I want to easily add and update challenges
so that I can expose more people to these cloud challenges.

## Overview
Clear details of what the minimum requirements are to complete this task
Challenges are currently in individual folders. This is good. A challenge.yml file with associated content needs to be added to each of them. 
See https://github.com/CTFd/ctfcli for details, and https://gitlab.com/jointcyberrange.nl/ctfcli-testchallenges for more examples, and workflows to test this. 

## Acceptance Criteria
- [ ] Security implications approved
- [ ] Works when deploying them to a CTFd instance. 

#### Non Functional Requirements/Wants
- [ ] 

#### External Documents / Links
See https://github.com/CTFd/ctfcli for details, and https://gitlab.com/jointcyberrange.nl/ctfcli-testchallenges for more examples, and workflows to test this.

**Comment by sethsec-bf** [comment]
Thank you so much for your interest in exposing CloudFoxable to more people @pve. And thanks for all of that info!  

It look me a few tries but I finally figured out that I can use the mirror command to grab what is in my instance and populate the challenge.yml. In my testing it seems that three preconditions need to be met for it to work: 

1. i configure the .ctf/config file with my api key and instance (and add it to .gitignore)
2. the challenge name folder needs to match exactly with the challenge name in the ctfd instance 
   - i'll have to rename each folder so it matches the name in the cloud instance
   - i'll have to fix all references to the folder names in the terraform code
3. the challenge name in the challenge.yaml needs to match exactly with the challenge name in the ctfd instance.  

Once 2 and three are done i'll test it out and push an update to main! 

I should have this done today or tomorrow.  Sorry for the delay. let me know if i'm missing anything.

**Comment by pve** [comment]
Will check later. We have updated https://gitlab.com/jointcyberrange.nl/ctfcli-testchallenges in the meantime to assist in testing this stuff out.

**Comment by sethsec-bf** [comment]
@pve - Challenge yamls have been added! Let me know if this is enough for you to deploy it to your own instance!
