### ISSUE TITLE
adding configuration for local stack for local AWS Environment 

### ISSUE THREAD

**Issue by redcatsec** [BishopFox/cloudfoxable#8]
As a person,
I want to learn security testing for AWS without any cost using localstack 
so that someone who dose not have the money for aws environment 

## Overview
I want to add  --endpoint-url configuration variable in the terraform variables 
https://docs.localstack.cloud/user-guide/integrations/aws-cli/

**Comment by sethsec-bf** [comment]
Hi @almosaiki! Sorry it took me so long to get back to you. 

I'm pretty sure you can do this right now if you download the terraform-local binary https://github.com/localstack/terraform-local. However, I will say that I tried to do the whole thing in localstack myself at first, and I found that not all services are supported by localstack so the terraform apply would fail.  

For what it's worth, if you create a new AWS account for this, you will be on the free tier and everything created should fall under the free tier (as long as you turn it off when you are done with the challenge).
